// Copyright (c) 2016, 2018, 2026, Oracle and/or its affiliates.  All rights reserved.
// This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
// Code generated. DO NOT EDIT.

// Generative AI Service Nl2sql API
//
// A description of the ReferenceService API. in progress
//

package generativeaidata

import (
	"encoding/json"
	"fmt"
	"github.com/oracle/oci-go-sdk/v65/common"
	"strings"
)

// JobOutput A JobOutput delivers content generated by the GenerateSQLJob to a given location, which corresponds with type-specific characteristics.
type JobOutput interface {
}

type joboutput struct {
	JsonData          []byte
	JobOutputLocation string `json:"jobOutputLocation"`
}

// UnmarshalJSON unmarshals json
func (m *joboutput) UnmarshalJSON(data []byte) error {
	m.JsonData = data
	type Unmarshalerjoboutput joboutput
	s := struct {
		Model Unmarshalerjoboutput
	}{}
	err := json.Unmarshal(data, &s.Model)
	if err != nil {
		return err
	}
	m.JobOutputLocation = s.Model.JobOutputLocation

	return err
}

// UnmarshalPolymorphicJSON unmarshals polymorphic json
func (m *joboutput) UnmarshalPolymorphicJSON(data []byte) (interface{}, error) {

	if data == nil || string(data) == "null" {
		return nil, nil
	}

	var err error
	switch m.JobOutputLocation {
	case "INLINE":
		mm := InlineJobOutput{}
		err = json.Unmarshal(data, &mm)
		return mm, err
	default:
		common.Logf("Received unsupported enum value for JobOutput: %s.", m.JobOutputLocation)
		return *m, nil
	}
}

func (m joboutput) String() string {
	return common.PointerString(m)
}

// ValidateEnumValue returns an error when providing an unsupported enum value
// This function is being called during constructing API request process
// Not recommended for calling this function directly
func (m joboutput) ValidateEnumValue() (bool, error) {
	errMessage := []string{}

	if len(errMessage) > 0 {
		return true, fmt.Errorf("%s", strings.Join(errMessage, "\n"))
	}
	return false, nil
}
